# services:
#   app:
#     image: php-app
#     ports:
#       - 8080:80
#     depends_on:
#       - database
#     stdin_open: true
#     tty: true
#   database:
#     image: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: test_db
#       MYSQL_USER: devuser
#       MYSQL_PASSWORD: devpass
#     ports:
#       - 9906:3306

version: "3.7"
services:
  web:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
  db:
    image: mysql
    volumes:
      - myapp:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: docker_database
    ports:
      - 3306:3306
volumes:
  myapp:
